const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const app = express();
const PORT = process.env.PORT || 5000;
app.use(cors());
app.use(express.json());
mongoose.connect('mongodb://localhost:27017/users').then(() => console.log("MongoDB connected.")).catch(err => console.error(err));
app.get('/', (req, res) => {res.send("Welcome to the project!");});
app.listen(PORT, () => {console.log(`Server running on port ${PORT}`);});